name: Keep Vidara Files Alive

on:
  schedule:
    # Berjalan otomatis pada tanggal 1 dan tanggal 16 setiap bulan jam 00:00 UTC (setiap 15 hari)
    - cron: '0 0 1,16 * *'
  workflow_dispatch: # Memungkinkan Anda menjalankan ini secara manual dari tab Actions

jobs:
  ping-links:
    runs-on: ubuntu-latest
    steps:
      - name: Akses URL Video Vidara
        run: |
          # Ganti URL di bawah ini dengan URL file/video Vidara Anda
          curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" -sL https://vidara.to/embed/contoh-id-video-anda
          
          echo "Akses berhasil dilakukan pada $(date)"
