name: Freedl Keep Alive & Auto Clean

on:
  schedule:
    # Berjalan otomatis seminggu sekali (Setiap hari Minggu jam 07:00 WIB)
    - cron: '0 0 * * 0'
  workflow_dispatch: # Tombol untuk tes jalankan manual kapan saja

jobs:
  ping-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          set-safe-directory: 'true'

      # Menginstal dependensi yang dibutuhkan skrip Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run keep alive script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        # Memproses seluruh isi links.txt secara runtut tanpa dibagi-bagi (menghindari conflict)
        run: python keep_alive.py 1 1

      # Proses simpan yang aman tanpa risiko tabrakan data paralel
      - name: Commit and Push if links.txt changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if ! git diff --quiet links.txt; then
            echo "Menemukan link mati, melakukan pembaruan ke repositori..."
            git add links.txt
            git commit -m "🧹 Auto-clean dead links"
            git push origin main
          else
            echo "Semua link aktif. Tidak ada perubahan."
          fi
